apiVersion: v1
kind: Pod
metadata:
  name: ccc-pvc-mount
spec:
  containers:
  - name: ccc-pvc-mount
    image: gitlab-registry.nrp-nautilus.io/skhan/dl_pytorch:4bd8b3be
    workingDir: /solaiman  # Updated working directory
    command: ["sh", "-lc", "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.notebook_dir=/solaiman"]
    resources:
      limits:
        memory: 12Gi
        cpu: 2
      requests:
        memory: 10Gi
        cpu: 2
    volumeMounts:
    - mountPath: /solaiman
      name: cloudcomp-data
  volumes:
    - name: cloudcomp-data
      persistentVolumeClaim:
        claimName: cloudcomp-data
