apiVersion: v1
kind: Pod
metadata:
  name: sknnh-resnet18-shell
spec:
  automountServiceAccountToken: false
  containers:
  - name: sknnh-resnet18-shell
    image: ubuntu:20.04
    workingDir: /data/dltrain
    command: ["/bin/sh", "-lc", "tail -f /dev/null"]  # keep pod alive for exec
    resources:
      limits:
        memory: 10Gi
        cpu: "1"
      requests:
        memory: 10Gi
        cpu: "1"
    volumeMounts:
    - name: cloudcomp-solaiman
      mountPath: /data/dltrain
  volumes:
  - name: cloudcomp-solaiman
    persistentVolumeClaim:
      claimName: cloudcomp-solaiman
  restartPolicy: Never
